' This file is used by Code Analysis to maintain SuppressMessage
' attributes that are applied to this project.
' Project-level suppressions either have no target or are given
' a specific target and scoped to a namespace, type, member, etc.

Imports System.Diagnostics.CodeAnalysis

<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CLSForm.btnPrtSights_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CLSForm.DrawBasicPlotForm")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CLSForm.PlotFixType(System.Int32)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CLSForm.PlotSightType(System.Int32)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CLSForm.SetCentralLatLong~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CLSForm.SetPlotInfoFields")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CLSForm.UnStringEP(System.String,System.Int32)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CustomPlot.btnPrtSights_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CustomPlot.DrawBasicPlotForm")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CustomPlot.PlotFixType(System.Int32)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CustomPlot.PlotSightType(System.Int32)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CustomPlot.SetandEditCentralLatLong~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CustomPlot.SetPlotInfoFields")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CustomPlot.SetPlotSideSize")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CustomPlot.UnStringEP(System.String,System.Int32)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.btnAddNew_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.btnExportGPX_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.btnUpdateExisting_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.DataGridView1_SelectionChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.EditPlanFields~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.EditUpdtFields~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.EvaluateDBPairs(System.Int32,System.Int32,System.Boolean)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.FindInstallAdvancedDR")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.FindInstallAdvancedPlan")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.FormSRF_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.GetDistanceDG(System.Int32,System.Int32)~System.Double")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.ParseLatLong(System.String)~System.Device.Location.GeoCoordinate")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DevForm.BuildTblFromDG")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DevForm.DGDev_CellValueChanged(System.Object,System.Windows.Forms.DataGridViewCellEventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DisplayEQTData.CnvtDec(System.Object)~System.String")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DisplayEQTData.CnvtEQT(System.Object)~System.String")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DisplayEQTData.CnvtHo(System.Object)~System.String")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DisplayEQTData.CnvtToDeg(System.Object)~System.String")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DisplayEQTData.DisplayAnalema")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DisplayEQTData.DisplayEQTData_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.btnUseLocation_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.BuildArrayFromscreen")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.CnvtHSStrtoDouble(System.Object)~System.Double")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.EditDRLatField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.EditDRLongField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.EditDSField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.EditFromAZField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.EditHEField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.EditToAZField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.PrepareSightArray")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.ZDParms.#ctor(System.String,System.Int32,System.Int32,System.Int32)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FixDG.btnCustomPlot_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FixDG.btnUseCLS_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FixDG.DGFix_SelectionChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FixDG.WriteFixScreen")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.btnCLSPlot_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.btnCustomPlot_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.cmdSave_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.DisplayPolaris")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.FormSRF_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.FormatAltitudeTxtBx")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.FormatDecTxtBx")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.FormatLHATxtBox")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.FormatTimeTxtBx")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.ScreenCapture")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSailings.cmdPoints_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSailings.cmdTraverse_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSailings.PointsM2")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNavMath.cmdCalculateToD_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNavMath.cmdConvert_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNavMath.DTLocA_ValueChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form60DST.cmdDistance_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form60DST.cmdSpeed_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form60DST.cmdTime_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTVMDC.DevInterpC")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTVMDC.DevInterpM")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTVMDC.DisplayTVMDC")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormLength.Calculate")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormLength.CalculateForFile(System.Double)~System.String")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.CheckDate~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.cmdCCW_MouseDown(System.Object,System.Windows.Forms.MouseEventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.cmdCW_MouseDown(System.Object,System.Windows.Forms.MouseEventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.cmdTwilights_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.CTimetoAngle(System.String)~System.Double")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplayData")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplayHorizonView")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplaySunRiseSunSet")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplayTwilights")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplayView")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.ExecCmdTwilights")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.FormSightPlan_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.RecyclePlan1Jpg")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.SelectTabToDisplay")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.Warning")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTwoBearings.cmdCalculateF2_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormMeridianDiagram.DisplayMerDiag")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTides.cmdTides_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormDevTable_frm.cmdClear_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormDevTable_frm.FormDevTable_frm_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.BuildEqtTable")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.cmdLAN_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.DisplayAlmanacData")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.DisplayAltitudeData")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.DisplayLANTime")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.DisplayLatitudeData")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.DisplayLongitudeByLAN")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.DisplayMeridianDiagram")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.FormNoonSight_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.btnCustomPlot_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.btnUseCLS_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.cmdFix_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.cmdSave_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.Display208")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.Display211")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.Display214")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.Display229")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.Display249")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.DisplayLOC")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.DisplayNASR")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.DisplaySadler")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.DisplaySTable")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.DisplayWeems")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.FormAltSR_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.frmAbout.frmAbout_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.btnCustomPlot_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.btnPlanSight_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.btnUseCLS_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.BuildArrayFromscreen")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.CnvtHSStrtoDouble(System.Object)~System.Double")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditDRLatField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditDRLongField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditDSField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditHEField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditHSField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditIEField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.FormatSightForPrint(CelestialTools.SightLog.SightEntry)~System.String")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.FormatSightForSave(CelestialTools.SightLog.SightEntry)~System.String")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.FormatSightintoDG(CelestialTools.SightLog.SightEntry)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.ParseLineIntoSLArray(System.String)~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.PerformNoonSight")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.PerformSRF")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.PrepareSightArray")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.SelectDGRow(System.DateTime,System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SRFTimeDiagram.CnvtDbltoDegMin(System.Double)~System.String")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SRFTimeDiagram.CnvtDbltoHrMin(System.Double)~System.String")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SRFTimeDiagram.DisplayTimeDiagram")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.TestDev.btnCompassDev_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.TestDev.btnMagDev_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CLSForm.SendMsgBx(System.String,System.Windows.Forms.MessageBoxIcon)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CSVUpdater.btnOpenCSV_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CSVUpdater.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CustomPlot.SendMsgBx(System.String,System.Windows.Forms.MessageBoxIcon)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.btnAddNew_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.btnCreateReportFile_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.btnExportGPX_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.btnOpenCSV_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.btnUpdateExisting_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.EditUpdtFields~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.FindInstallAdvancedDR")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.SaveDataGrid")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DevForm.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DevForm.OpenDevFile")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DevForm.SaveDevDataGrid")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.btnDeleteSight_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.btnExit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.btnNewLog_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.btnOpenLog_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.btnShowSharedLoc_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.CommonYesNoMsgBox(System.String)~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.EditDRLatField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.EditDRLongField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.EditDSField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.EditHEField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.ExecClearScreenFields")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.ExecFilePrint")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.ExecFileSave")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.ParseLineIntoSLArray(System.String)~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.cboBody_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.cboPressure_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.cboTemperature_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.DisplayLOC")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.DisplayPolaris")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.FormatAltitudeTxtBx")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.FormatDecTxtBx")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.FormatLHATxtBox")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.FormatSightTxtBx")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.FormatTimeTxtBx")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.optStdTPYes_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.optZDUT_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSRF.SendMsgBx(System.String,System.Windows.Forms.MessageBoxIcon)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormArcTime.Display")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormArcTime.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSailings.cmdTraverse_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSailings.DisplayCD")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSailings.DisplaySD")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSailings.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSailings.optGreatCircle_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSailings.optMercatorE_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSailings.optMercatorS_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSailings.optMethod1_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSailings.optMidLat_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormCTSSOA.cmdCalculate_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormCTSSOA.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormDistances.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNavMath.cmdCalculateToD_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNavMath.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form60DST.cmdDistance_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form60DST.cmdSpeed_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form60DST.cmdTime_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form60DST.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTVMDC.chkChartVar_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTVMDC.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTVMDC.txtChange_TextChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTVMDC.txtCVMin_TextChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormLength.Calculate")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormLength.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormLength.FormLength_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormLength.txtLDeg_TextChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormIandC.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplayAzAltText(System.Windows.Point)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplayData")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplaySunMoon")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplaySunRiseSunSet")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplayTwilights")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.MoonData")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.MoonPosition")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.optZDUT_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.SendMsgBx(System.String,System.Windows.Forms.MessageBoxIcon)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.Warning")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormMoBoard.cmdCalculate_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormMoBoard.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTwoBearings.cmdCalculateC_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTwoBearings.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTwoBearings.optComp_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTwoBearings.optMag_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTwoBearings.optRel_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTwoBearings.optTrue_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormMeridianDiagram.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTides.cmdTides_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormTides.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormCurrents.cmdCurrents_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormCurrents.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormVertical.cmdCalcVert_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormVertical.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormVertical.txtHeight_TextChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormDevTable_frm.cmdClear_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormDevTable_frm.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.cboPressure_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.cboTemperature_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.cmdLAN_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.DisplayAlmanacData")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.DisplayAltitudeData")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.DisplayLANTime")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.DisplayLatitudeData")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.optStdTPYes_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.optZDUT_CheckedChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.SendMsgBx(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form7.btnOpenLocList_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form7.cmdRemoveLocation_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form7.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form7.ExecFileSave")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form7.Form7_FormClosing(System.Object,System.Windows.Forms.FormClosingEventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.Display208")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.Display211")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.Display214")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.Display229")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.Display249")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.DisplayLOC")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.DisplayNASR")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.DisplaySadler")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.DisplaySTable")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.DisplayWeems")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormAltSR.SendMsgBx(System.String,System.Windows.Forms.MessageBoxIcon)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.frmPointsOnGCR.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.frmPointsOnRhumb.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.btnExit_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.btnNewLog_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.btnOpenLog_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditDRLatField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditDRLongField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditDSField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditHEField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditHSField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditIEField~System.Boolean")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.ErrorMsgBox(System.String)")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.ExecClearScreenFields")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.ExecDataSaveasCSV")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.ExecFileSave")>
<Assembly: SuppressMessage("Globalization", "CA1303:Do not pass literals as localized parameters", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.ParseLineIntoSLArray(System.String)~System.Boolean")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CSVUpdater.btnOpenCSV_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.btnOpenCSV_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.EditPlanFields~System.Boolean")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.EditUpdtFields~System.Boolean")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DevForm.OpenDevFile")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.btnOpenLog_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.EditDRLatField~System.Boolean")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.EditDRLongField~System.Boolean")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.EditDSField~System.Boolean")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.EditHEField~System.Boolean")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.FormatSightintoDG(CelestialTools.FavoriteLocations.FavoriteLoc)")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.SaveDisplayBMFname")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormDevTable_frm.ReadDevTblFile")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form7.btnOpenLocList_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.HelpV2.LoadTextFiletoTxtBx(System.String,System.Windows.Forms.RichTextBox@)")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Print_Renamed.printTxtFile1(System.String)")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.btnOpenLog_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditDRLatField~System.Boolean")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditDRLongField~System.Boolean")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditDSField~System.Boolean")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditHEField~System.Boolean")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditHSField~System.Boolean")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.EditIEField~System.Boolean")>
<Assembly: SuppressMessage("Design", "CA1031:Do not catch general exception types", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.FormatSightintoDG(CelestialTools.SightLog.SightEntry)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.ZTInfo.LoadDG")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.ZTInfo.cbLocAZD_MouseEnter(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.ZTInfo.cbLocBZone_MouseEnter(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.ZTInfo.cboLocAZD_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.ZTInfo.cboLocBZD_SelectedIndexChanged(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.ZTInfo.EditFields~System.Boolean")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CLSForm.DrawBasicPlotForm")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CLSForm.FirstTimeInitGraphics")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CLSForm.FirstTimeInitGraphics")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CLSForm.PlotFixType(System.Int32)")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CLSForm.PlotSightType(System.Int32)")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CSVUpdater.btnOpenCSV_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CustomPlot.DrawBasicPlotForm")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CustomPlot.FirstTimeInit")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CustomPlot.FirstTimeInit")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CustomPlot.PlotFixType(System.Int32)")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.CustomPlot.PlotSightType(System.Int32)")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DevForm.OpenDevFile")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DevForm.SaveDevDataGrid")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DevForm.SaveDevDataGrid")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DisplayEQTData.DisplayAnalema")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.btnOpenLog_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.ExecFilePrint")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.ExecFilePrint")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.ExecFileSave")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.ExecFileSave")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.FavoriteLocations_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.PrintDocument1_PrintPage(System.Object,System.Drawing.Printing.PrintPageEventArgs)")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FavoriteLocations.PrintDocument1_PrintPage(System.Object,System.Drawing.Printing.PrintPageEventArgs)")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormLength.FormLength_Load(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplayHorizonView")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplayHorizonView")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplaySunRiseSunSet")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplaySunRiseSunSet")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplayView")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DisplayView")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DrawCelestialCircles")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormSightPlan.DrawCelestialCircles")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormMeridianDiagram.DisplayMerDiag")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormMeridianDiagram.DisplayMerDiag")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormMeridianDiagram.Ellipses")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormMeridianDiagram.Ellipses")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormMeridianDiagram.StrWidth(System.String,System.Drawing.Font)~System.Int32")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.FormNoonSight.DisplayMeridianDiagram")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form7.btnOpenLocList_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form7.ExecFileSave")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Form7.ExecFileSave")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Print_Renamed.pd_PrintPage(System.Object,System.Drawing.Printing.PrintPageEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Print_Renamed.PrintScreen(System.Drawing.Rectangle)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Print_Renamed.PrintScreen(System.Windows.Rect)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.Print_Renamed.printTxtFile1(System.String)")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.btnOpenLog_Click(System.Object,System.EventArgs)")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.ExecDataSaveasCSV")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.ExecFileSave")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.ExecFileSave")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.PrintDocument1_PrintPage(System.Object,System.Drawing.Printing.PrintPageEventArgs)")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SightLog.PrintDocument1_PrintPage(System.Object,System.Drawing.Printing.PrintPageEventArgs)")>
<Assembly: SuppressMessage("Style", "IDE0017:Simplify object initialization", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SRFTimeDiagram.DisplayTimeDiagram")>
<Assembly: SuppressMessage("Reliability", "CA2000:Dispose objects before losing scope", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.SRFTimeDiagram.DisplayTimeDiagram")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.ProcessAddNew")>
<Assembly: SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification:="<Pending>", Scope:="member", Target:="~M:CelestialTools.DeckLogUpdate.ProcessUpdateExisting")>
